import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const golos = Golos_Text({
	weight: ["400", "500", "600", "700", "800", "900"],
	style: ["normal"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${golos.className} antialiased`}>
				<div>
					<Header />
					<main className="flex flex-col">{children}</main>
				</div>
			</body>
		</html>
	);
}
