import type { Metadata } from "next";
import { Golos_Text } from "next/font/google";
import "./globals.css";
import Layout from "@/modules/layout";
import ContactModalProvider from "@/modules/contact/components/contact-modal-provider";

const golos = Golos_Text({
	weight: ["400", "500", "600", "700", "800", "900"],
	style: ["normal"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${golos.className} antialiased`}>
				<ContactModalProvider />
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
