import type { Metadata } from "next"
import Layout from "@/modules/layout"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Layout>
      {children}
    </Layout>
  )
}