name: Build Docker images

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-dockerfile-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: cr.yandex
          username: ${{ secrets.YANDEX_USERNAME }}
          password: ${{ secrets.YANDEX_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            cr.yandex/crps3cqv4rgnku2mtmdf/parus-frontend:latest
          platforms: linux/amd64
          build-args: |
            NEXT_PUBLIC_DEFAULT_REGION=ru
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            YMAPS3_API_KEY=${{ secrets.YMAPS3_API_KEY }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            REVALIDATE_SECRET=${{ secrets.REVALIDATE_SECRET }}
            S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
            S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}
            S3_REGION=${{ secrets.S3_REGION }}
            S3_BUCKET=${{ secrets.S3_BUCKET }}
            S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}

      - name: Call API after Docker push
        run: curl "${{ secrets.DEPLOY_URL }}"
